### ISSUE TITLE
Decide the order in which assignments should be listed on the assignments view page

### ISSUE THREAD

**Issue by dschinde** [dschinde/homework-organizer#3]

**Comment by klongtran** [comment]
Should it be sorted by due dates?

**Comment by dschinde** [comment]
Yes, but I'm wondering how it should be sorted within any given date.

**Comment by klongtran** [comment]
Hmm maybe allow for a deadline time as well, then sort them within a day
using that time? If tie, then sort alphabetically?

**Comment by clarah2** [comment]
or it could just be by the order in which the classes are listed in the
settings page? or alphabetically by classes? I think it would be good to
have the assignments listed by class in the same order as they are every
day, so for whichever method we use, doing it by the class rather than the
assignment would be better, in my opinion.  Other than that, I don't think
it makes much of a difference to the user whichever method we pick.  But if
we do have an option to choose a time that the assignment is due, then it
will matter more to incorporate this.

**Comment by dschinde** [comment]
Yeah, that makes sense. Currently I'm thinking:
1. Sort by class in the order in which they are added
2. Sort by deadline time, if specified
3. Sort alphabetically if the deadline time is not specified, or if there is a tie

**Comment by clarah2** [comment]
accomplished
